<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('prices')->insert(
            [
                [
                'cosmetologies_id'=>'1',
                'services_id'=>'1',
                'cost'=>'850',
                'created_at'=>'2019-07-01'
                ],
                [
                'cosmetologies_id'=>'1',
                'services_id'=>'2',
                'cost'=>'1300',
                'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'3',
                    'cost'=>'1400',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'4',
                    'cost'=>'700',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'5',
                    'cost'=>'550',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'6',
                    'cost'=>'2500',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'7',
                    'cost'=>'850',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'8',
                    'cost'=>'1600',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'9',
                    'cost'=>'1450',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'1',
                    'services_id'=>'10',
                    'cost'=>'880',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'2',
                    'services_id'=>'5',
                    'cost'=>'850',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'2',
                    'services_id'=>'6',
                    'cost'=>'1100',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'2',
                    'services_id'=>'7',
                    'cost'=>'999',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'2',
                    'services_id'=>'8',
                    'cost'=>'1400',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'2',
                    'services_id'=>'9',
                    'cost'=>'1000',
                    'created_at'=>'2019-07-01'
                ],
                [
                'cosmetologies_id'=>'3',
                'services_id'=>'11',
                'cost'=>'950',
                'created_at'=>'2019-07-01'
                 ],
                [
                    'cosmetologies_id'=>'3',
                    'services_id'=>'12',
                    'cost'=>'1200',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'3',
                    'services_id'=>'13',
                    'cost'=>'1100',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'3',
                    'services_id'=>'14',
                    'cost'=>'1050',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'3',
                    'services_id'=>'15',
                    'cost'=>'1300',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'4',
                    'services_id'=>'1',
                    'cost'=>'850',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'4',
                    'services_id'=>'2',
                    'cost'=>'950',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'4',
                    'services_id'=>'3',
                    'cost'=>'1050',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'4',
                    'services_id'=>'4',
                    'cost'=>'1200',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'4',
                    'services_id'=>'5',
                    'cost'=>'750',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'11',
                    'cost'=>'1800',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'12',
                    'cost'=>'1850',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'13',
                    'cost'=>'1200',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'14',
                    'cost'=>'1700',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'15',
                    'cost'=>'1900',
                    'created_at'=>'2019-07-01'
                ],
                [
                    'cosmetologies_id'=>'5',
                    'services_id'=>'9',
                    'cost'=>'850',
                    'created_at'=>'2019-07-01'
                ]
            ]);
    }
}
